### ISSUE TITLE
Site Accessibility

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1242]
Tackle in this order

- [x] Home page
 All non guides/docs pages - (downloads, blogs, community, support, etc)
- [x] Downloads 
- [x] Blogs
- [x] Community
- [x] Support
- [x] Contribute
- [x] Guides
   - [x] Guide - non interactive
   - [x] Guide - interactive
- [x] Docs (keep in mind we are moving to antora)
- [x] Reference - subpages
   - [x] Java EE API - No DAP Issues
   - [x] MicroProfile API - No DAP issues
   - [x] Server Config
   - [x] Server Features
   - [x] Server Commands
   - [x] General

Also, tackle DAP, tabbing, then Jaws
- [x] DAP
- [x] JAWs
  
For any text/image that is part of logo name that has DAP violation please see https://github.com/openliberty/openliberty.io/issues/1242#issuecomment-576752714

**Comment by dmorgant** [comment]
Pages without any updates:

- Community page had no DAP updates

**Comment by aknguyen7** [comment]
- Contribute page has 1 DAP violation on Open Liberty text but it does not need to meet this requirement since it's a text that is part of logo

![image](https://user-images.githubusercontent.com/30509453/72820982-76114d00-3c35-11ea-84ea-e789a8e40cc9.png)


![image](https://user-images.githubusercontent.com/30509453/72821052-904b2b00-3c35-11ea-9aef-641be4daf49e.png)

**Comment by mbroz2** [comment]
Can we add a comment into the html that summarizes the above comment so that anyone running DAP in the future that gets that error immediately sees that it's not an issue and doesn't have to spend any time investigating further?

**Comment by dmorgant** [comment]
Accessibility and the NavBar in the header -  getting DAP color contrast issues when the NavBar elements in the header appear over one of the dark blue-ish backgrounds.

The bootstrap \<nav> element is defined with a transparent background.  The NavBar menu links are defined as children of the bootstrap \<nav> element.  Below the \<nav> element in the html is another \<div> element that the \<nav> element is sitting on top of.  This \<div> element is given a background-color or background-image that we see (dark blues).  When DAP processes, it reads the text color and the background color of the \<nav> element for the navigation links and is falsely reporting a color contrast issue because it is not comparing the color of the text with the actual color of the background the links are sitting on top of. 

FYI...setting the text color of the navigation links to black will cause these contrast issues to go away, but visibly the text is near impossible to read.

1) _Docs, Get Started, Support,_ and _Fork Code_ links
![image](https://user-images.githubusercontent.com/29490139/72999703-5b6dde00-3dc5-11ea-9a89-d5413f6433c4.png)

The color contrast issue for these 4 links is because the background-image is set in the #intro_background div and the navbar containing the links sits on top of this div.

![image](https://user-images.githubusercontent.com/29490139/73002366-8c501200-3dc9-11ea-9511-56a6e5032527.png)

![image](https://user-images.githubusercontent.com/29490139/72999989-d0411800-3dc5-11ea-8082-3e9f4e22378c.png)

2) _Guides_ and _Reference_ links
![image](https://user-images.githubusercontent.com/29490139/73000202-1eeeb200-3dc6-11ea-8047-c7b25a420089.png)

This nav bar (A) is overlayed with a \#header_background div (B) that has the actual background color (#313653).
![image](https://user-images.githubusercontent.com/29490139/73001208-b1dc1c00-3dc7-11ea-89b9-d7d7e512c75b.png)

**Comment by dmorgant** [comment]
**Accessibility and the Hamburger Icon on the Docs pages.**
The Hamburger Icon for the navigation elements is displayed when the page width is made small, replacing the navbar elements that are otherwise across the page header.

The behavior of the hamburger icon on the Docs pages differs from the ones that appear on other pages.  When selected from the Docs pages the hamburger icon acts as a toggle. The navbar elements are displayed at the top of the page content and the content is slid down underneath these elements.  
![image](https://user-images.githubusercontent.com/29490139/73021229-caaaf880-3dec-11ea-9b11-e3a164a3ec81.png)
You can scroll down to the page content. Reselecting the hamburger icon toggles the navbar elements to slide out of view.

On other pages, the page content is replaced with the navbar elements and an 'X' replaces the hamburger icon.
![image](https://user-images.githubusercontent.com/29490139/73021926-2de95a80-3dee-11ea-8d63-8e3fdb198a4e.png)
You cannot access the page content by scrolling.  You must use the 'X' to hide the navbar elements and return to the main page.

On the Docs pages, the Hamburger Icon is defined with a read-only \<div> that provides a label for the Icon.  It has the class _.sr-only_ which is a bootstrap class intended for use **only** by screen readers as it hides the element from the layout of the rendered page.  In this situation, the \<span> with class _.sr-only_  is used as a label for the Hamburger Icon for the screen reader to read.
![image](https://user-images.githubusercontent.com/29490139/73024521-56278800-3df3-11ea-908a-0fc596c945ba.png)

DAP is giving a color contrast violation for this \<span> with class _.sr-only_ which is invalid since the \<span> is always hidden.  Assigning a `color: white;` to the \<span> does remove the violation, but should not be necessary since the \<span> will never be seen.

**Comment by dmorgant** [comment]
**Collapsible Navbar using Bootstrap**
As mentioned above, on the Docs pages, the Hamburger Icon is used to toggle the navigation bar on small screens.   This is all done using Bootstrap classes.   When the Hamburger Icon is clicked, the navigation bar is displayed vertically just above the content.  The \<div> containing the navbar elements is given the **_aria-expanded_** attribute **by Bootstrap** to indicate if the navbar was expanded or not.   This is not a valid use of the **_'aria-expanded'_** attribute and is causing a DAP exception.   However, we cannot control the addition of this attribute and still use Bootstrap.

From what I can see, the **_aria-expanded_** attribute is being used to save off the current expanded state of the navbar.  If, when the window is small, you click on the Hamburger Icon and expand the navbar, then resize the window so the Hamburger Icon is hidden and the navbar elements go back to the top of the page in the header, the div still records that aria-expanded is true.  Then, after you re-resize the window smaller again, since aria-expanded was set to true the navbar items are shown again.  If it was set to false, they aren't shown when you re-resize.

**Comment by dmorgant** [comment]
There is a new DAP requirement (see https://aat.w3ibm.mybluemix.net/token/de8df1ce-98b3-4bb3-9c26-f1e43383ab4a/637a6695-357b-4877-948c-14a25de53d98/latest///doc/w3/help/en-US/idhi_accessibility_check_g1059.html):

For a complex data table, th and td elements must be related via scope or headers
The rule detected a complex table where th and td elements are not programmatically related.

In data tables, there are <th> header cells and <td> data cells. Every header cell must be a heading for some set of data cells, and every data cell must have a header. In complex table structures, data cells could be associated with more than one row and/or column headers.

Within the reference documents, there was a table at 
Docs->Reference->General->Logging and tracing
where I was unable to fix this violation because the table elements are built by ascii-doctor.
