### ISSUE TITLE
Updates for MicroProfile 6.0 and Jakarta EE 10

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2953]
- [x]  Item 1: Replace Jakarta 9 with Jakarta 10 and MP 5 with MP 6 for publishing (keep 8 and 4 respectively for those on the old namespace) https://github.com/OpenLiberty/openliberty.io/issues/2979
- [ ] (Not a must-have) #3096 (assigned to @natalie-bernhard )
- [x]  Item 3: Add new MP and Jakarta EE packages to starter https://github.com/OpenLiberty/start.openliberty.io/issues/162
- [x]  Item 4: Add new MP6 Javadocs (assigned to @steven1046) https://github.com/OpenLiberty/docs-javadoc/pull/36
- [x] Item 5: Add new EE10 Javadocs (assigned to @kinueng) https://github.com/OpenLiberty/docs-javadoc/pull/41 https://github.com/OpenLiberty/docs/pull/6475

**Comment by natalie-bernhard** [comment]
Past versions will retain MP5 and EE9, new packages (once MP6 and EE10 are released) should only have MP6 and EE10.  We should also add logic to account for the case in which MP5 and MP6 are both present, which should make it so that only the newer package renders (and the same with EE9 and EE10).

Edit: For Item 1

**Comment by kinueng** [comment]
Item 2:
Need to follow up on whether MP can be excluded from Jakarta packages. My confusion is most likely due to my lack of understanding on how MP 6 is packaged.

**Comment by steven1046** [comment]
The MP 6.0 javadoc is added here: https://github.com/OpenLiberty/docs-javadoc/pull/36.
I will generate an adoc file for the doc page hosting it.

**Comment by kinueng** [comment]
The must have items have been delivered.
